WITH JANUARY_BOOK_SALES AS (
	SELECT * FROM BOOK_SALES WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES FROM JANUARY_BOOK_SALES AS J
#SELECT * FROM JANUARY_BOOK_SALES AS J
JOIN BOOK AS B ON J.BOOK_ID=B.BOOK_ID
JOIN AUTHOR AS A ON B.AUTHOR_ID=A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID ASC, CATEGORY DESC;
