SELECT I.ITEM_ID, ITEM_NAME, RARITY FROM ITEM_TREE AS T
JOIN ITEM_INFO AS I
ON T.ITEM_ID=I.ITEM_ID
WHERE I.ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID 
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY I.ITEM_ID DESC;
