-- CAR_RENTAL_COMPANY_CAR 테이블에 할인된 금액 FEE 컬럼을 추가한다. (30일 이상으로)
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY에서 대여 가능한 car id를 중복 없이 구한다.
WITH CAR_TABLE AS (
	SELECT CAR_ID, A.CAR_TYPE, DAILY_FEE, DISCOUNT_RATE, FLOOR(30*DAILY_FEE * (100-DISCOUNT_RATE)/100) AS DISCOUNTED_FEE FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B ON A.CAR_TYPE = B.CAR_TYPE WHERE DURATION_TYPE = "30일 이상"
)
SELECT CAR_ID, CAR_TYPE, DISCOUNTED_FEE AS FEE FROM CAR_TABLE WHERE CAR_ID NOT IN (
	SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01') AND (CAR_TYPE = "세단" OR CAR_TYPE="SUV")
 AND DISCOUNTED_FEE >=500000 AND DISCOUNTED_FEE < 2000000 ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;