WITH RECURSIVE tmp AS(
	SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    
    SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID, tmp.GENERATION+1
    FROM ECOLI_DATA JOIN tmp ON ECOLI_DATA.PARENT_ID = tmp.ID
)

SELECT COUNT(*) AS COUNT, GENERATION FROM tmp 
WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION ORDER BY GENERATION ASC;