-- 코드를 입력하세요
WITH FIRST_HALF_AGG AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM FIRST_HALF GROUP BY FLAVOR
)
,JULY_AGG AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR
)

SELECT F.FLAVOR  
FROM FIRST_HALF_AGG AS F 
JOIN JULY_AGG AS J 
ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER+J.TOTAL_ORDER) DESC
LIMIT 3;