-- 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역 필터링
SELECT APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, APNT_YMD
FROM APPOINTMENT AS A JOIN PATIENT AS P ON A.PT_NO=P.PT_NO JOIN DOCTOR AS D ON A.MDDR_ID=D.DR_ID
WHERE DATE(APNT_YMD)='2022-04-13' AND A.MCDP_CD='CS' AND APNT_CNCL_YN='N'
ORDER BY APNT_YMD ASC;
