-- 연도별 가장 큰 대장균 크기 구하기
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (
	SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA WHERE YEAR(DIFFERENTIATION_DATE) = YEAR
) - SIZE_OF_COLONY AS YEAR_DEV, ID FROM ECOLI_DATA ORDER BY YEAR ASC, YEAR_DEV ASC;