-- CATEGORY를 기준으로 GROUP BY
-- CATEGORY가 '과자', '국', '김치', '식용유'인 경우만 출력
WITH MAX_PRICE_TABLE AS(
	SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT
	WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
	GROUP BY CATEGORY
	ORDER BY MAX_PRICE DESC
)

SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F JOIN MAX_PRICE_TABLE AS M ON F.CATEGORY = M.CATEGORY
WHERE F.PRICE = M.MAX_PRICE
ORDER BY MAX_PRICE DESC;